
name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.3.app
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
    - name: Checkout
      uses: actions/checkout@master
    - name: recon
      run: |
        ls
        pwd
        cd AzureSample
    - name: Build App
      run: xcodebuild -project "AzureSample/AzureSample.xcodeproj" -scheme "AzureSample" -destination "generic/platform=iOS"
      
      
      
#     - name: Build archive
#       run: |
#         xcodebuild -sdk iphoneos -project Azure\ sample.xcodeproj \
#           -configuration Release -scheme Azure-sample \
#           -derivedDataPath DerivedData \
#           -archivePath DerivedData/Archive/Azure-sample archive

#       run: |
#         xcodebuild -exportArchive \
#           -archivePath DerivedData/Archive/Azure-sample.xcarchive \
#           -exportOptionsPlist provisioning/App-Store.plist \
#           -exportPath DerivedData/ipa


#       - uses: yukiarrr/ios-build-action@v0.5.0
#         with:
#           project-path: AzureSample/AzureSample.xcodeproj
